import { ActiveUserRole, ClientKind } from "./user.js";

export enum MessageType {
  HELLO = 'hello',
  ERROR = 'error',
  CURRENT_STATE = 'current_state',
  AUTH_FAILURE = 'auth_failure',
  AUTH_REQUEST = 'auth_request',
  AUTH_SUCCESS = 'auth_success',
  ROBOT_LIST_REQUEST = 'robot_list_request',
  ROBOT_LIST_RESPONSE = 'robot_list_response',
  ROBOT_ACQUIRE_REQUEST = 'robot_acquire_request',
  ROBOT_ACQUIRE_RESPONSE = 'robot_acquire_response',
  ROBOT_RELEASE_REQUEST = 'robot_release_request',
  ROBOT_RELEASE_RESPONSE = 'robot_release_response',
  ROBOT_STOLEN_MESSAGE = 'robot_stolen_message',
  FORWARD_MESSAGE_TO_ROBOT_REQUEST = 'forward_message_to_robot_request',
  SIGNAL_P2POFFER_REQUEST = 'signal.p2poffer_request',
  SIGNAL_P2PANSWER_REQUEST = 'signal.p2panswer_request',
  SIGNAL_P2PICECANDIDATE_REQUEST = 'signal.p2picecandidate_request',
  SIGNAL_PEER_DISCONNECTED = 'signal.peer_disconnected',
}

export interface Robot {
  robotUserId: number;
  name: string;
  available: boolean;
  isControllerConnected: boolean;
  isVideoConnected: boolean;
}

export interface Message {
  timestamp: number;
  type: MessageType;
}

export interface ErrorMessage extends Message {
  type: MessageType;
  error: string;
  stacktrace?: string | string[] | null | undefined;
  eObj?: any; // for flexibility. Proably will never get used.
}

export interface AuthRequest extends Message {
  type: MessageType.AUTH_REQUEST;
  username: string;
  password: string;
  clientKind: ClientKind;
}

export interface AuthFailureResponse extends ErrorMessage {
  type: MessageType.AUTH_FAILURE;
}

export interface AuthSuccessResponse extends Message {
  type: MessageType.AUTH_SUCCESS;
  name: string;
  role: ActiveUserRole;
}

export interface RobotListRequest extends Message {
  type: MessageType.ROBOT_LIST_REQUEST;
}

export interface RobotListResponse extends Message {
  type: MessageType.ROBOT_LIST_RESPONSE;
  robots: Robot[];
}

export interface RobotAcquireRequest extends Message {
  type: MessageType.ROBOT_ACQUIRE_REQUEST;
  robotUserId: number;
  steal: boolean; // if true, will steal the robot even if it's currently acquired by another user
}

export interface RobotSuccessfullyAcquiredResponse extends Message {
  type: MessageType.ROBOT_ACQUIRE_RESPONSE;
  robotUserId: number;
  controllerSessionId: number;
  videoSessionId: number;
  name: string;
}

export interface RobotAcquireFailureResponse extends ErrorMessage {
  type: MessageType.ROBOT_ACQUIRE_RESPONSE;
}

export interface RobotReleaseRequest extends Message {
  type: MessageType.ROBOT_RELEASE_REQUEST;
  robotUserId: number;
}

export interface RobotReleaseResponse extends Message {
  type: MessageType.ROBOT_RELEASE_RESPONSE;
  robotUserId: number;
}

// Generic message type. Most likely will be used for debugging and modifying device registers.
export interface ForwardMessageToRobotRequest extends Message {
  type: MessageType.FORWARD_MESSAGE_TO_ROBOT_REQUEST;
  robotUserId: number;
  payload: any; // for flexibility, since we don't know what kind of messages the frontend will want to send to the robot
  sendRegardlessOfOwnership?: boolean;
}

export interface SignalP2POfferRequest extends Message {
  type: MessageType.SIGNAL_P2POFFER_REQUEST;
  targetId: number; // session id of the target peer
  offer: any; // will be generated by the WebRTC lib
}

export interface SignalP2PAnswerRequest extends Message {
  type: MessageType.SIGNAL_P2PANSWER_REQUEST;
  targetId: number; // session id of the target peer
  answer: any; // will be generated by the WebRTC lib
}

export interface SignalP2PIceCandidateRequest extends Message {
  type: MessageType.SIGNAL_P2PICECANDIDATE_REQUEST;
  targetId: number; // session id of the target peer
  candidate: any; // will be generated by the WebRTC lib
}

export interface SignalP2PPeerDisconnectedMessage extends Message {
  type: MessageType.SIGNAL_PEER_DISCONNECTED;
  targetId: number;
}

export interface RobotStolenByAnotherUserMessage extends Message {
  type: MessageType.ROBOT_STOLEN_MESSAGE;
  robotUserId: number;
}

export interface CurrentStateMessage extends Message {
  type: MessageType.CURRENT_STATE;
  authenticated: boolean;
  userName?: string;
  userRole?: ActiveUserRole;
  robotUserId?: number;
}
